services:
  app:
    container_name: "application-server"
    image: "jupyter/scipy-notebook"
    restart: always
    volumes:
      - .:/workspace:cached
      - work:/home/jovyan/work
    ports:
      - 8888:8888
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined

volumes:
  work:

networks:
  app-network:
    external: true
